version: '3'

services:
  # Database
  db:
    image: postgres

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Celery worker
  celery:
    image: celery
    environment:
     - CELERY_BROKER_URL=amqp://admin:mypass@rabbit
    links:
      - rabbit
    depends_on:
      - rabbit

  web:
    build: "."
    command: "/entrypoint.sh"
    environment:
     - DJANGO_SETTINGS_MODULE=mainsite.settings_docker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery